app:
  baseUrl: "https://bfhldevapigw.healthrx.co.in"
  generatePath: "/hiring/generateWebhook/JAVA"
  fallbackSubmitPath: "/hiring/testWebhook/JAVA"
  name: "Clifford Jestin"
  regNo: "22BHI10155"
  email: "cliffordjestin2022@vitbhopal.ac.in"

logging:
  level:
    root: INFO
    com.example.hiring: DEBUG
